<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // Common
    'ID'          => 'ИД',
    'Close'       => 'Закрыть',
    'View'        => 'Просмотр',
    'Adding'      => 'Добавление',
    'Editing'     => 'Редактирование',
    'Deleting'    => 'Удаление',
    'Add'         => 'Добавить',
    'Add more'    => 'Добавить ещё',
    'Edit'        => 'Редактировать',
    'Fast edit'   => 'Быстрое редатирование',
    'Delete'      => 'Удалить',
    'Restore'     => 'Восстановить',
    'Hide'        => 'Скрыть',
    'Show'        => 'Показать',
    'Save'        => 'Сохранить',
    'Apply'       => 'Применить',
    'Cancel'      => 'Отмена',
    'Undefined'   => 'Не определено',
    'Status'      => 'Статус',
    'Create time' => 'Время создания',
    'Add time'    => 'Время добавления',
    'Loading'     => 'Загрузка',
    'Actions with selected items' => 'Действия с выбранными элементами',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Active records' => 'Активные',
    'Inactive records' => 'Неактивные',
    'Deleted records'=> 'Удалённые',
    'Records'     => 'записей',
    'Link'        => 'Ссылка',
    'Links'       => 'Ссылки',
    'No records found' => 'Записи не найдены',
    'No items' => 'Нет элементов',
    'Record has been deleted' => 'Запись удалена',
    'Record has been restored' => 'Запись восстановлена',
    'Record has been published' => 'Запись опубликована',
    'Record has been hidden' => 'Запись скрыта',
    'Hidden' => 'Скрыто',
    'Published' => 'Опубликовано',
    'Deleted' => 'Удалено',
    'Yes' => 'Да',
    'No' => 'Нет',
    'Site' => 'Сайт',
    'Upload' => 'Загрузить',
    'Download' => 'Скачать',
    'Last update' => 'Последнее обновление',

    // Errors
    'Page not found' => 'Страница не найдена',
    'Record not found' => 'Запись не найдена',
    'Forbidden' => 'Доступ запрещён',
    'The file must be with the extension "{ext}"' => 'Файл должен быть с расширением "{ext}"',
    'Error saving file' => 'Ошибка сохранения файла',
    'File upload error' => 'Ошибка загрузки файла',

    // User and roles
    'Access'        => 'Доступ',
    'Welcome'       => 'Добро пожаловать',
    'Your name'     => 'Ваше имя',
    'Full name'     => 'ФИО',
    'User'          => 'Пользователь',
    'Users'         => 'Пользователи',
    'Email'         => 'Email',
    'Password'      => 'Пароль',
    'Retype password' => 'Повторите пароль',
    'Old password'   => 'Старый пароль',
    'New password'   => 'Новый пароль',
    'Access token'  => 'Ключ доступа',
    'Role'          => 'Роль',
    'Roles'         => 'Роли',
    'Parent role'   => 'Родительская роль',
    'Last activity' => 'Последняя активность',
    'Language'      => 'Язык',
    'Time zone'     => 'Часовой пояс',
    'Login'         => 'Вход',
    'Sign in'       => 'Войти',
    'Logout'        => 'Выход',
    'Sign out'      => 'Выйти',
    'Remember me'   => 'Запомнить меня',
    'Active'        => 'Активный',
    'Inactive'      => 'Неактивный',
    'Blocked'       => 'Заблокированный',
    'Incorrect email or password' => 'Неверный логин или пароль',
    'Incorrect password' => 'Неверный пароль',
    'Activate' => 'Активировать',
    'Profile' => 'Профиль',
    'Import' => 'Импорт',
    'Phone' => 'Телефон',
    'User name' => 'Имя пользователя',
    'No users found' => 'Пользователей не обнаружено',
    'User has been deleted' => 'Пользователь удалён',
    'User has been restored' => 'Пользователь восстановлен',
    'No roles found' => 'Ролей не обнаружено',
    'Role name' => 'Название роли',
    'Parent role' => 'Родительская роль',
    'You must first delete all child roles' => 'Сначала необходимо удалить все дочерние роли',
    'First, you must remove all users of this role or move them to another role' => 'Сначала необходимо удалить всех пользователей этой роли либо перенести их в другую роль',
    'Role has been deleted' => 'Роль удалена',
    'Role has been restored' => 'Роль восстановлена',
    'Administrator rules' => 'Права администратора',
    'You can not delete the current user' => 'Нельзя удалить текущего пользователя',
    'A user with such an email is already registered' => 'Пользователь с таким e-mail уже зарегистрирован',
    'A user with such an phone is already registered' => 'Пользователь с таким телефоном уже зарегистрирован',
    'Notify' => 'Уведомления',
    'Rule' => 'Правило',
    'Rules' => 'Правила',
    'Access is denied to this section for your group.' => 'Для вашей группы запрещён доступ в данный раздел.',
    'Address name' => 'Название',
    'Address' => 'Адрес',

    // Manage
    'Panel' => 'Панель',
    'Settings' => 'Настройки',
    'Common' => 'Общие',
    'List' => 'Список',
    'Settings have been saved' => 'Настройки сохранены',
    'Data has been saved' => 'Данные сохранены!',
    'Record has been saved' => 'Запись сохранена',
    'File has been uploaded' => 'Файл успешно загружен',
    'Manage' => 'Управление',
    'Description' => 'Описание',
    'Forms' => 'Формы',
    'Select value' => 'Выберите значение',

    // Variables
    'Variables' => 'Переменные',
    'Variable' => 'Переменная',
    'Variable name' => 'Имя',
    'Variable value' => 'Значение',

    // Templates
    'Templates' => 'Шаблоны',
    'Template' => 'Шаблон',
    'Template name' => 'Название шаблона',
    'Template content' => 'Содержание шаблона',
    'Layout' => 'Файл шаблона',
    'You need to add the value of {{{content}}} to the template content' => 'Необходимо добавить в содержание шаблона значение {{{content}}}',

    // Pages
    'Pages' => 'Страницы',
    'Page'  => 'Страница',
    'Title' => 'Заголовок',
    'Page name' => 'Название страницы',
    'Slug'  => 'Адрес страницы',
    'Parent page' => 'Родительская страница',
    'Page content' => 'Содержание страницы',
    'Parent section' => 'Родительский раздел',
    'Page height' => 'Высота страницы',
    'Include to sitemap.xml' => 'Включить в sitemap.xml',
    'Page order' => 'Позиция в подразделе',
    'Main' => 'Основное',
    'This value must be unique within a subsection.' => 'Данное значение должно быть уникальным в рамках подраздела.',

    // Menu
    'Menu' => 'Меню',
    'Menu item' => 'Пункт меню',
    'Parent menu' => 'Родительское меню',

    // Mail
    'Mail' => 'Почта',
    'Mails' => 'Отправления',
    'Mail queue' => 'Очередь сообщений',
    'Mail templates' => 'Шаблоны сообщений',
    'Mail views' => 'Представления сообщений',
    'Mail servers' => 'Почтовые серверы',
    'Mail attachments' => 'Почтовые вложения',

    'Mail settings' => 'Настройки почты',
    'Send time' => 'Время отправки',
    'To email' => 'Адресат',
    'Subject' => 'Тема',
    'Body text' => 'Сообщение',
    'Body html' => 'Сообщение HTML',
    'Send errors' => 'Ошибки отправки',
    'Service name' => 'Название сервиса',
    'SMTP host' => 'SMTP-сервер',
    'SMTP port' => 'SMTP-порт',
    'SMTP user' => 'SMTP-пользователь',
    'SMTP password' => 'SMTP-пароль',
    'SMTP secure' => 'SMTP-безопасность',
    'From email' => 'Адрес отправителя',
    'From name' => 'Имя отправителя',
    'Reply to' => 'Адрес для ответа',
    'Sended'   => 'Отправлено',
    'Error'    => 'Ошибка',
    'Sending'  => 'Отправка',
    'Waiting'  => 'Ожидание',
    'Resend' => 'Отправить заново',
    'Send' => 'Отправить',

    // Options
    'Option' => 'Опция',
    'Options' => 'Опции',
    'Option value' => 'Значение',
    'User role for registration' => 'Группа пользователя для регистрации',
    'Site address' => 'Адрес сайта',

    // CSS
    'CSS' => 'CSS',
    'CSS Name' => 'Название CSS',
    'Path' => 'Путь',
    'Content' => 'Содержание',
    'Embedded style' => 'Встроенный стиль',
    'External style' => 'Внешний стиль',

    // JS
    'JS Name' => 'Название JS',
    'Embedded script' => 'Встроенный скрипт',
    'External script' => 'Внешний скрипт',

    // Site settings
    'Site title' => 'Общий заголовок сайта',
    'Site title position' => 'Позиция заголовка сайта',
    'Site title separator' => 'Разделитель заголовка сайта',
    'Main page' => 'Главная страница',
    'Page extension' => 'Расширение страницы',
    'After' => 'В конце',
    'Before' => 'В начале',
    'Scheme' => 'Схема',

    // Property
    'Property' => 'Характеристика',
    'Properties' => 'Характеристики',
    'Entity' => 'Сущность',
    'Property name' => 'Название свойства',
    'Config' => 'Конфигурация',
    'Filter field' => 'Фильтр по полю',
    'Filter value' => 'Фильтр по значению',
    'View table' => 'Просмотр в таблице',
    'View record' => 'Просмотр в записи',
    'View site' => 'Отображать на сайте',
    'Internal search' => 'Внутренний поиск по полю',
    'External search' => 'Внешний поиск по полю',
    'Property order' => 'Порядок',
    'Record ID' => 'Идентификатор записи',
    'Variant' => 'Вариант',

    'Market' => 'Магазин',
    'Product category' => 'Категория товаров',
    'Product categories' => 'Категории товаров',
    'Subcategory' => 'Подкатегория',
    'Subcategories' => 'Подкатегории',
    'Category name' => 'Название категории',
    'Add category' => 'Добавить категорию',
    'Add product' => 'Добавить товар',
    'Parent category' => 'Родительская категория',
    'Product' => 'Товар',
    'Products' => 'Товары',
    'Total' => 'Всего',
    'Category description' => 'Описание категории',
    'Category filter' => 'Фильтр категории',
    'In the filter' => 'В фильтре',
    'Not in filter' => 'Не в фильтре',
    'In the item card' => 'В карточке товара',
    'Not in the item card' => 'Не в карточке товара',
    'Product name' => 'Название товара',
    'Product description' => 'Описание товара',
    'Ext code' => 'Внешний код',
    'Int code' => 'Внутренний код',
    'Price' => 'Цена',
    'Old price' => 'Старая цена',
    'Specifications' => 'Характеристики',
    'Warehouse' => 'Склад',
    'Photos' => 'Фотографии',
    'Quantity available' => 'Количество в наличии',
    'Unit' => 'Единица измерения',
    'Packing quantity' => 'Количество в упаковке',
    'Not specified' => 'Не указан',
    'Vendor' => 'Производитель',
    'Promo' => 'Акции',
    'Discount' => 'Скидка',
    'New value' => 'Новое значение',
    'New property' => 'Новое свойство',

    // Orders
    'Delivery date' => 'Дата доставки',
    'Issue date' => 'Дата выдачи',
    'Fio' => 'ФИО',
    'Your phone' => 'Ваш телефон',
    'Your email' => 'Ваша электронная почта',
    'Address' => 'Адрес доставки',
    'Payment type' => 'Способ оплаты',
    'Delivery type' => 'Способ доставки',
    'Delivery price' => 'Стоимость доставки',
    'Product discount' => 'Скидка на товары',
    'Delivery discount' => 'Скидка на доставку',
    'Order comment' => 'Комментарий к заказу',

    // Reviews
    'Review' => 'Отзыв',
    'Reviews' => 'Отзывы',
    'Reviewer' => 'Имя',
    'Review text' => 'Текст отзыва',

    // Callbacks
    'Callback'  => 'Заказ обратного звонка',
    'Callbacks' => 'Заказы обратного звонка',


    // Delivery address
    'Delivery address'   => 'Адрес доставки',
    'Delivery addresses' => 'Адреса доставки',

    // Фильтры категорий
    'Category filter'  => 'Фильтр категорий',
    'Category filters' => 'Фильтры категорий',

    // Cross sales
    'Cross sales' => 'Кросс-сэйл товары',
    'Cross sale'  => 'Кросс-сэйл товар',

    // Product document
    'Product document' => 'Документ товара',
    'Product documents' => 'Документы товаров',

    // Product labels
    'Product label' => 'Метка товара',
    'Product labels' => 'Метки товаров',
    'Label' => 'Метка',
    'Labels' => 'Метки',
    'Widget' => 'Тэг',
    'Font color' => 'Цвет текста',
    'Background color' => 'Цвет фона',

    // Product label relation
    'Product label relation'  => 'Связь метки с товарами',
    'Product label relations' => 'Связи меток с товарами',

    // Product photo
    'Product photo' => 'Фото товара',
    'Product photos' => 'Фото товаров',

    // Vendors
    'Vendor' => 'Производитель',
    'Vendors' => 'Производители',

    // Subscriber
    'Subscriber' => 'Подписчик',
    'Subscribers' => 'Подписчики',

    // Product property
    'Product property' => 'Характеристика товаров',
    'Product properties' => 'Характеристики товаров',

    // Resently products
    'Resently product' => 'Недавнно просмотренный товар',
    'Resently products' => 'Недавно просмотренные товары',

    // Shopcart
    'Shopcart' => 'Корзина',

    // Shop order
    'Shop order' => 'Заказ магазина',
    'Shop orders' => 'Заказы магазина',

    // Shop order positions
    'Order position' => 'Позиция заказа',
    'Order positions' => 'Позиции заказа',

    // Shop payments
    'Shop payment' => 'Платёж магазина',
    'Shop payments' => 'Платежи магазина',

    // Feedback
    'Feedback' => 'Обратная связь',
    'Message'  => 'Сообщение',

    // Mail Templates
    'Mail template' => 'Шаблон отправления',
    'Mail templates' => 'Шаблоны отправлений',
    'Template ID' => 'Идентификатор шаблона',

    // Banners
    'Banner'  => 'Баннер',
    'Banners' => 'Баннеры',
    'Banner text' => 'Текст баннера',

    // SUbscribe
    'Subscribe' => 'Рассылка',
    'Subscribes' => 'Рассылки',
    'Mail subject' => 'Тема письма',
    'Mail text' => 'Текст письма',
    'Draft' => 'Черновик',


    'Photo' => 'Фото',
    'Country' => 'Страна',
    'City' => 'Город',
    'Phones' => 'Телефоны',
    'Rate' => 'Оценка',

    'Amount' => 'Сумма',
    'Period' => 'Период',
    'Current month' => 'Текущий месяц',
    'Manual' => 'Вручую',
    'Year' => 'Год',
    'Month' => 'Месяц',
    'January' => 'Январь',
    'February' => 'Февраль',
    'March' => 'Март',
    'April' => 'Апрель',
    'May' => 'Май',
    'June' => 'Июнь',
    'July' => 'Июль',
    'August' => 'Август',
    'September' => 'Сентябрь',
    'October' => 'Октябрь',
    'November' => 'Ноябрь',
    'December' => 'Декабрь',

    'of January' => 'января',
    'of February' => 'февраля',
    'of March' => 'марта',
    'of April' => 'апреля',
    'of May' => 'мая',
    'of June' => 'июня',
    'of July' => 'июля',
    'of August' => 'августа',
    'of September' => 'сентября',
    'of October' => 'октября',
    'of November' => 'ноября',
    'of December' => 'декабря',
];